/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.arnold;

import edu.badpals.arnold.main.ArnoldMain;
import org.junit.Test;
import static org.junit.Assert.*;

public class ArnoldTest {
    @Test public void appHasAGreeting() {
        ArnoldMain classUnderTest = new ArnoldMain();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
