/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.badpals.arnold.main;

public class ArnoldMain {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new ArnoldMain().getGreeting());
    }
}
